### ISSUE TITLE
Weitere Übersetzung bis Kapitel 27 (42?) sind vorhanden. 

### ISSUE THREAD

**Issue by TobiasWegener** [entorb/hpmor-de#8]
Guten Tag zusammen,
super das sich das auch jemand für die Deutsche Version macht!:)
Hier ein paar links, vielleicht kann man das ja mit einbinden: [Hörbuch](https://www.youtube.com/watch?v=8PC5jbfk_wo), und hier der Link zu seiner eigenen [Übersetzung](https://www.fanfiktion.de/s/5c793dfe000a402030774dc7/1/Harry-Potter-und-die-Methoden-der-Rationalitaet-Ubersetzung-HPMOR).

Ich habe schon gesehen das ein ekook Ordner gibt eine Epub Version wäre natürlich fantastisch.
Vielen Dank für das fantastische Projekt, falls ich so etwas lieber woanders schreiben sollte, bin ich ganz offen für konstruktive Kritik.
Schönen Gruß Tobias

**Comment by entorb** [comment]
Moin Tobias,
Vielen Dank für die Hinweise! Dann gibt es ja schon 3 Übersetzungen ;-) Habe beide Links in die [Readme](https://github.com/entorb/hpmor-de/blob/master/README.md) aufgenommen.

ePub Versionen in [DE](https://entorb.net/hpmor/) und [EN](https://github.com/rrthomas/hpmor/releases/latest) hatte ich letztes Jahr schon mal erstellt. Aber die DE Übersetzung und ihr Schriftsatz sind verbesserungswürdig, daher dieses Projekt ;-). Ich hoffe ich finde motivierte Mitstreiter, alleine wird es lange dauern...

LG Torben
